server {
    listen 80;

    # Página personalizada para bloqueos (Capa de Respuesta)
    error_page 403 /403.html;
    proxy_intercept_errors on;

    # ══════════════════════════════════════════════════════════════════
    # 1. INTEGRACIÓN FRONTEND (React)
    # ══════════════════════════════════════════════════════════════════
    location / {
        auth_request /validate; # CAPA DE SEGURIDAD ML

        proxy_pass http://pyme-app-front:3000; 
        
        root /usr/share/nginx/html/pyme;
        index pyme_index.html;
        try_files $uri $uri/ /pyme_index.html;
        
        error_page 403 /403.html;


        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Guardar logs para auditoría
        #access_log /var/log/nginx/waf_access.log;
    }

    # ══════════════════════════════════════════════════════════════════
    # 2. INTEGRACIÓN BACKEND (PHP / API de Inventario)
    # ══════════════════════════════════════════════════════════════════
    location /api/ {
        auth_request /validate; # Inspección obligatoria para la API

        # Redirige las peticiones al backend (ATEL-BACK)
        proxy_pass http://pyme-app-back:80; 

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location = /validate {
        internal;

        proxy_pass http://ml-engine:8000/waf_core;

        proxy_pass_request_body on;
        proxy_set_header Content-Length "";

        # Cabeceras críticas para que la IA analice el ataque
        proxy_set_header X-Original-URI    $request_uri;
        proxy_set_header X-Original-Method $request_method;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header Content-Type      $content_type;
    }

    location = /403.html {
        root /usr/share/nginx/html;
        internal;
    }
}